#include "onnx/inference_engine.h"
#include <iostream>
#include <sstream>
#include <algorithm>
#include <chrono>
#include <cstring>

// ONNX Runtime C++ API (header-only wrapper)
#include <onnxruntime_cxx_api.h>

// SentencePiece processor
#include <sentencepiece_processor.h>

// Embedded model symbols (generated by xxd -i)
#ifdef EMBED_MODEL
extern "C" {
    extern const unsigned char model_onnx[];
    extern const unsigned int model_onnx_len;
    extern const unsigned char spiece_model[];
    extern const unsigned int spiece_model_len;
}
#endif

namespace llmzip {

// ============================================================================
// PIMPL implementation details
// ============================================================================
struct InferenceEngine::Impl {
    Ort::Env env{nullptr};
    Ort::SessionOptions session_options{nullptr};
    std::unique_ptr<Ort::Session> session{nullptr};
    Ort::MemoryInfo memory_info{nullptr};

    sentencepiece::SentencePieceProcessor sp_processor;

    std::string model_path;
    int64_t vocab_size = 32128;   // T5 default
    int64_t max_seq_len = 512;
    int64_t max_new_tokens = 150;  // max tokens to generate
    bool session_loaded = false;

    // Input/output names (populated after session creation)
    std::vector<const char*> input_names;
    std::vector<const char*> output_names;
    std::vector<Ort::AllocatedStringPtr> input_names_ptrs;
    std::vector<Ort::AllocatedStringPtr> output_names_ptrs;

    // T5 special token IDs
    int64_t pad_token_id = 0;
    int64_t eos_token_id = 1;

    ~Impl() {
        session.reset();
    }

    // ----------------------------------------------------------------
    // SentencePiece tokenize — returns encoder token IDs (no special prefix)
    // ----------------------------------------------------------------
    std::vector<int64_t> tokenize(const std::string& input) {
        std::vector<int> sp_ids;
        sp_processor.Encode(input, &sp_ids);

        // Truncate to max_seq_len - 1 (leave room for pad/separator)
        if (sp_ids.size() > (size_t)max_seq_len - 1)
            sp_ids.resize(max_seq_len - 1);

        std::vector<int64_t> tokens;
        tokens.reserve(sp_ids.size());

        // T5 SentencePiece doesn't add BOS by default, but we start with pad_token
        // For encoder input, we just pass the SentencePiece IDs directly
        for (int id : sp_ids) {
            // Map extra_ids (32000-32099) back to valid range if needed
            tokens.push_back(id);
        }

        return tokens;
    }

    // ----------------------------------------------------------------
    // SentencePiece detokenize
    // ----------------------------------------------------------------
    std::string detokenize(const std::vector<int64_t>& tokens) {
        std::vector<int> sp_ids;
        sp_ids.reserve(tokens.size());
        for (int64_t id : tokens) {
            if (id == pad_token_id || id == eos_token_id) continue;
            sp_ids.push_back(static_cast<int>(id));
        }

        std::string text;
        sp_processor.Decode(sp_ids, &text);
        return text;
    }

    // ----------------------------------------------------------------
    // T5 decoder step — run fused model, return logits for last position
    // ----------------------------------------------------------------
    bool decoder_step(const std::vector<int64_t>& encoder_ids,
                      const std::vector<int64_t>& decoder_ids,
                      std::vector<float>& logits_out)
    {
        // Build full input: concat(encoder_ids, decoder_ids)
        // T5 expects padding to max_seq_len
        std::vector<int64_t> full_ids(max_seq_len, pad_token_id);
        std::vector<int64_t> attention_mask(max_seq_len, 0);

        // Copy encoder IDs
        for (size_t i = 0; i < encoder_ids.size(); ++i) {
            full_ids[i] = encoder_ids[i];
            attention_mask[i] = 1;
        }

        // Add separator (eos token between encoder and decoder)
        size_t sep_pos = encoder_ids.size();
        full_ids[sep_pos] = eos_token_id;  // </s> as separator
        attention_mask[sep_pos] = 1;

        // Copy decoder IDs after separator
        for (size_t i = 0; i < decoder_ids.size(); ++i) {
            size_t p = sep_pos + 1 + i;
            if (p >= (size_t)max_seq_len) break;
            full_ids[p] = decoder_ids[i];
            attention_mask[p] = 1;  // decoder gets attention too in T5
        }

        std::vector<int64_t> input_shape = {1, max_seq_len};

        // Build encoder_hidden_states placeholder (unused in fused model)
        const int64_t d_model = 512;
        std::vector<int64_t> hidden_shape = {1, (int64_t)max_seq_len, d_model};
        size_t hidden_elems = 1 * max_seq_len * d_model;
        std::vector<float> dummy_hidden(hidden_elems, 0.0f);
        Ort::Value hidden_tensor = Ort::Value::CreateTensor<float>(
            memory_info, dummy_hidden.data(), dummy_hidden.size(),
            hidden_shape.data(), hidden_shape.size());

        // Build ONNX inputs matching model's expected order
        std::vector<Ort::Value> ort_inputs;
        std::vector<const char*> ort_input_names;

        for (size_t i = 0; i < input_names.size(); ++i) {
            const std::string& name = input_names[i];
            ort_input_names.push_back(input_names[i]);

            if (name == "input_ids") {
                auto tensor = Ort::Value::CreateTensor<int64_t>(
                    memory_info, full_ids.data(), full_ids.size(),
                    input_shape.data(), input_shape.size());
                ort_inputs.push_back(std::move(tensor));
            } else if (name == "encoder_attention_mask") {
                auto tensor = Ort::Value::CreateTensor<int64_t>(
                    memory_info, attention_mask.data(), attention_mask.size(),
                    input_shape.data(), input_shape.size());
                ort_inputs.push_back(std::move(tensor));
            } else if (name == "encoder_hidden_states") {
                // Clone hidden_tensor each iteration
                auto tensor = Ort::Value::CreateTensor<float>(
                    memory_info, dummy_hidden.data(), dummy_hidden.size(),
                    hidden_shape.data(), hidden_shape.size());
                ort_inputs.push_back(std::move(tensor));
            } else {
                // Unknown input — int64 zeros
                std::vector<int64_t> dummy(1, 0);
                auto tensor = Ort::Value::CreateTensor<int64_t>(
                    memory_info, dummy.data(), dummy.size(),
                    std::vector<int64_t>{1, 1}.data(), 2);
                ort_inputs.push_back(std::move(tensor));
            }
        }

        // Build output names
        std::vector<const char*> ort_output_names;
        for (size_t i = 0; i < output_names.size(); ++i)
            ort_output_names.push_back(output_names[i]);

        // Run
        auto output_tensors = session->Run(
            Ort::RunOptions{nullptr},
            ort_input_names.data(), ort_inputs.data(), ort_inputs.size(),
            ort_output_names.data(), ort_output_names.size());

        if (output_tensors.empty())
            return false;

        // Find logits output (last output = logits)
        size_t logits_idx = output_tensors.size() - 1;
        auto type_info = output_tensors[logits_idx].GetTensorTypeAndShapeInfo();
        auto elem_type = type_info.GetElementType();
        auto shape = type_info.GetShape();

        if (elem_type != ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT)
            return false;
        if (shape.size() < 2)
            return false;

        auto* logits_data = output_tensors[logits_idx].GetTensorMutableData<float>();
        size_t total = type_info.GetElementCount();

        int64_t seq_len = shape[shape.size() - 2];
        int64_t voc_size = shape[shape.size() - 1];

        if (seq_len < 1 || voc_size < 1)
            return false;

        // Take logits from the last non-padding position in decoder portion
        // full_ids are padded to max_seq_len, so we look at the actual active length
        int64_t active_len = sep_pos + 1 + (int64_t)decoder_ids.size();
        int64_t last_pos = std::min(active_len - 1, seq_len - 1);
        if (last_pos < 0) last_pos = seq_len - 1;

        int64_t offset = last_pos * voc_size;
        int64_t num_logits = std::min<int64_t>(voc_size, 32128);
        logits_out.assign(logits_data + offset, logits_data + offset + num_logits);

        return true;
    }
};

// ============================================================================
// InferenceEngine public API
// ============================================================================
InferenceEngine::InferenceEngine()
    : pimpl_(std::make_unique<Impl>()) {
}

InferenceEngine::~InferenceEngine() = default;

// ---------------------------------------------------------------------------
// initialize_embedded
// ---------------------------------------------------------------------------
bool InferenceEngine::initialize_embedded() {
#ifdef EMBED_MODEL
    try {
        // --- 1. Load SentencePiece processor from embedded model ---
        if (spiece_model_len > 0) {
            auto status = pimpl_->sp_processor.LoadFromSerializedProto(
                std::string(reinterpret_cast<const char*>(spiece_model), spiece_model_len));
            if (!status.ok()) {
                std::cerr << "[InferenceEngine] SentencePiece load failed: "
                          << status.ToString() << "\n";
                initialized_ = false;
                return false;
            }
            std::cerr << "[InferenceEngine] SentencePiece loaded ("
                      << (spiece_model_len / 1024) << " KB, vocab="
                      << pimpl_->sp_processor.GetPieceSize() << ")\n";
        } else {
            std::cerr << "[InferenceEngine] Embedded spiece.model is empty\n";
            initialized_ = false;
            return false;
        }

        // --- 2. Load ONNX model from embedded model ---
        const size_t model_size = model_onnx_len;
        if (model_size == 0) {
            std::cerr << "[InferenceEngine] Embedded ONNX model is empty\n";
            initialized_ = false;
            return false;
        }

        pimpl_->env = Ort::Env(ORT_LOGGING_LEVEL_WARNING, "llmzip-embedded");
        pimpl_->session_options = Ort::SessionOptions();
        pimpl_->session_options.SetIntraOpNumThreads(2);
        pimpl_->session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);

        pimpl_->session = std::make_unique<Ort::Session>(
            pimpl_->env, model_onnx, model_size, pimpl_->session_options);
        pimpl_->model_path = "[embedded]";
        pimpl_->session_loaded = true;

        // Query input/output names
        Ort::AllocatorWithDefaultOptions allocator;
        size_t num_inputs = pimpl_->session->GetInputCount();
        for (size_t i = 0; i < num_inputs; ++i) {
            auto name = pimpl_->session->GetInputNameAllocated(i, allocator);
            pimpl_->input_names_ptrs.push_back(std::move(name));
            pimpl_->input_names.push_back(pimpl_->input_names_ptrs.back().get());
        }
        size_t num_outputs = pimpl_->session->GetOutputCount();
        for (size_t i = 0; i < num_outputs; ++i) {
            auto name = pimpl_->session->GetOutputNameAllocated(i, allocator);
            pimpl_->output_names_ptrs.push_back(std::move(name));
            pimpl_->output_names.push_back(pimpl_->output_names_ptrs.back().get());
        }

        pimpl_->memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);

        initialized_ = true;
        std::cout << "[InferenceEngine] Loaded embedded model (" << (model_size / 1048576) << " MB)\n";

        // Debug: print input info
        std::cerr << "[InferenceEngine] Model inputs:\n";
        for (size_t i = 0; i < pimpl_->input_names.size(); ++i) {
            auto type_info = pimpl_->session->GetInputTypeInfo(i);
            auto tensor_info = type_info.GetTensorTypeAndShapeInfo();
            auto shape = tensor_info.GetShape();
            std::string type_str;
            auto elem = tensor_info.GetElementType();
            if (elem == ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT) type_str = "float32";
            else if (elem == ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64) type_str = "int64";
            else if (elem == ONNX_TENSOR_ELEMENT_DATA_TYPE_INT32) type_str = "int32";
            else type_str = "type=" + std::to_string(elem);
            std::cerr << "  [" << i << "] " << pimpl_->input_names[i] << " : " << type_str << " shape=[";
            for (size_t d = 0; d < shape.size(); ++d) {
                if (d > 0) std::cerr << ",";
                if (shape[d] < 0) std::cerr << "?";
                else std::cerr << shape[d];
            }
            std::cerr << "]\n";
        }
        std::cerr << "[InferenceEngine] Model outputs:\n";
        for (size_t i = 0; i < pimpl_->output_names.size(); ++i) {
            auto type_info = pimpl_->session->GetOutputTypeInfo(i);
            auto tensor_info = type_info.GetTensorTypeAndShapeInfo();
            auto shape = tensor_info.GetShape();
            std::cerr << "  [" << i << "] " << pimpl_->output_names[i] << " shape=[";
            for (size_t d = 0; d < shape.size(); ++d) {
                if (d > 0) std::cerr << ",";
                if (shape[d] < 0) std::cerr << "?";
                else std::cerr << shape[d];
            }
            std::cerr << "]\n";
        }

        return true;
    } catch (const Ort::Exception& e) {
        std::cerr << "[InferenceEngine] Embedded model init error: " << e.what() << std::endl;
        initialized_ = false;
        return false;
    }
#else
    std::cerr << "[InferenceEngine] Model not embedded (compile with -DEMBED_MODEL=ON)\n";
    initialized_ = false;
    return false;
#endif
}

// ---------------------------------------------------------------------------
// initialize — load model from file
// ---------------------------------------------------------------------------
bool InferenceEngine::initialize(const std::string& model_path) {
    if (model_path.empty()) {
        return initialize_embedded();
    }

    try {
        pimpl_->env = Ort::Env(ORT_LOGGING_LEVEL_WARNING, "llmzip");
        pimpl_->session_options = Ort::SessionOptions();
        pimpl_->session_options.SetIntraOpNumThreads(2);
        pimpl_->session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);

        pimpl_->session = std::make_unique<Ort::Session>(
            pimpl_->env, model_path.c_str(), pimpl_->session_options);
        pimpl_->model_path = model_path;
        pimpl_->session_loaded = true;

        Ort::AllocatorWithDefaultOptions allocator;
        size_t num_inputs = pimpl_->session->GetInputCount();
        for (size_t i = 0; i < num_inputs; ++i) {
            auto name = pimpl_->session->GetInputNameAllocated(i, allocator);
            pimpl_->input_names_ptrs.push_back(std::move(name));
            pimpl_->input_names.push_back(pimpl_->input_names_ptrs.back().get());
        }
        size_t num_outputs = pimpl_->session->GetOutputCount();
        for (size_t i = 0; i < num_outputs; ++i) {
            auto name = pimpl_->session->GetOutputNameAllocated(i, allocator);
            pimpl_->output_names_ptrs.push_back(std::move(name));
            pimpl_->output_names.push_back(pimpl_->output_names_ptrs.back().get());
        }

        pimpl_->memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
        initialized_ = true;
        return true;
    } catch (const Ort::Exception& e) {
        std::cerr << "[InferenceEngine] ONNX init error: " << e.what() << std::endl;
        initialized_ = false;
        return false;
    }
}

// ---------------------------------------------------------------------------
// compress_text — autoregressive seq2seq decoding with SentencePiece
// ---------------------------------------------------------------------------
InferenceResult InferenceEngine::compress_text(const std::string& input) {
    InferenceResult result;
    result.success = false;

    if (!initialized_) {
        result.error_message = "Engine not initialized";
        return result;
    }

    try {
        auto start = std::chrono::steady_clock::now();

        // 1. Tokenize input with SentencePiece → encoder IDs
        std::vector<int64_t> encoder_ids = pimpl_->tokenize(input);
        std::cerr << "[T5] Encoder input: " << input.size() << " chars -> "
                  << encoder_ids.size() << " tokens\n";

        // 2. Autoregressive decoding loop
        std::vector<int64_t> decoder_ids;
        decoder_ids.reserve(pimpl_->max_new_tokens);
        decoder_ids.push_back(pimpl_->pad_token_id);  // start with <pad>

        bool eos_generated = false;
        for (int step = 0; step < pimpl_->max_new_tokens; ++step) {
            std::vector<float> logits;
            if (!pimpl_->decoder_step(encoder_ids, decoder_ids, logits)) {
                std::cerr << "[T5] decoder_step failed at step " << step << "\n";
                break;
            }

            // Argmax over vocabulary
            int best_id = 0;
            float best_val = logits[0];
            for (size_t v = 1; v < logits.size(); ++v) {
                if (logits[v] > best_val) {
                    best_val = logits[v];
                    best_id = static_cast<int>(v);
                }
            }

            if (best_id == pimpl_->eos_token_id) {
                eos_generated = true;
                break;
            }

            decoder_ids.push_back(best_id);

            // Safety: stop if decoder gets too long
            if (decoder_ids.size() >= (size_t)pimpl_->max_seq_len / 2)
                break;
        }

        // 3. Detokenize with SentencePiece (skip pad, keep all others)
        std::string compressed = pimpl_->detokenize(decoder_ids);
        std::cerr << "[T5] Generated " << decoder_ids.size()
                  << " tokens" << (eos_generated ? " (EOS)" : "") << "\n";

        // 4. Fallback: if output is empty or too similar to input, return input as-is
        if (compressed.empty()) {
            compressed = input;
            result.confidence_score = 0.0f;
        } else if (compressed.size() >= input.size() * 0.95) {
            // Model didn't actually compress — keep original
            compressed = input;
            result.confidence_score = 0.3f;
        } else {
            result.confidence_score = 0.85f;
        }

        result.output_text = compressed;
        result.success = true;

        auto end = std::chrono::steady_clock::now();
        result.inference_time_ms = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();

    } catch (const Ort::Exception& e) {
        result.error_message = "ONNX inference error: " + std::string(e.what());
        result.output_text = input;
        result.confidence_score = 0.0f;
    } catch (const std::exception& e) {
        result.error_message = "Inference error: " + std::string(e.what());
        result.output_text = input;
        result.confidence_score = 0.0f;
    }

    return result;
}

// ---------------------------------------------------------------------------
// decompress_text
// ---------------------------------------------------------------------------
InferenceResult InferenceEngine::decompress_text(const std::vector<uint8_t>& compressed_data) {
    InferenceResult result;
    result.success = false;

    if (!initialized_) {
        result.error_message = "Engine not initialized";
        return result;
    }

    try {
        auto start = std::chrono::steady_clock::now();

        // Convert binary data to string
        std::string input_str(reinterpret_cast<const char*>(compressed_data.data()),
                               compressed_data.size());

        // Tokenize with SentencePiece
        std::vector<int64_t> encoder_ids = pimpl_->tokenize(input_str);

        // Generate (decompress = expand)
        std::vector<int64_t> decoder_ids;
        decoder_ids.reserve(pimpl_->max_new_tokens);
        decoder_ids.push_back(pimpl_->pad_token_id);

        for (int step = 0; step < pimpl_->max_new_tokens; ++step) {
            std::vector<float> logits;
            if (!pimpl_->decoder_step(encoder_ids, decoder_ids, logits))
                break;

            int best_id = 0;
            float best_val = logits[0];
            for (size_t v = 1; v < logits.size(); ++v) {
                if (logits[v] > best_val) {
                    best_val = logits[v];
                    best_id = static_cast<int>(v);
                }
            }

            if (best_id == pimpl_->eos_token_id)
                break;

            decoder_ids.push_back(best_id);

            if (decoder_ids.size() >= (size_t)pimpl_->max_seq_len / 2)
                break;
        }

        std::string decompressed = pimpl_->detokenize(decoder_ids);
        if (decompressed.empty())
            decompressed = input_str; // fallback

        result.output_text = decompressed;
        result.success = true;

        auto end = std::chrono::steady_clock::now();
        result.inference_time_ms = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();

    } catch (const Ort::Exception& e) {
        result.error_message = "ONNX decompress error: " + std::string(e.what());
        result.output_text = "(decompress fallback)";
    }

    return result;
}

// ---------------------------------------------------------------------------
// get_model_info
// ---------------------------------------------------------------------------
std::string InferenceEngine::get_model_info() const {
    if (!initialized_)
        return "Not initialized";
    std::ostringstream oss;
    oss << "Model: " << pimpl_->model_path << "\n";
    oss << "Inputs: " << pimpl_->input_names.size() << "\n";
    for (const auto& name : pimpl_->input_names)
        oss << "  - " << name << "\n";
    oss << "Outputs: " << pimpl_->output_names.size() << "\n";
    for (const auto& name : pimpl_->output_names)
        oss << "  - " << name << "\n";
    oss << "Vocab: " << pimpl_->vocab_size << "\n";
    oss << "Tokenizer: SentencePiece (" << pimpl_->sp_processor.GetPieceSize() << " pieces)\n";
    oss << "Max seq: " << pimpl_->max_seq_len << "\n";
    oss << "Max new tokens: " << pimpl_->max_new_tokens;
    return oss.str();
}

std::vector<int64_t> InferenceEngine::tokenize_input(const std::string& input) {
    return pimpl_->tokenize(input);
}

std::string InferenceEngine::detokenize_output(const std::vector<int64_t>& tokens) {
    return pimpl_->detokenize(tokens);
}

} // namespace llmzip