#include "onnx/inference_engine.h"
#include <iostream>
#include <sstream>
#include <algorithm>
#include <chrono>
#include <cstring>
#include <filesystem>

#include <onnxruntime_cxx_api.h>
#include <sentencepiece_processor.h>

// Embedded models (generated by xxd -i)
#ifdef EMBED_MODEL
extern "C" {
    extern const unsigned char spiece_model[];
    extern const unsigned int spiece_model_len;
    extern const unsigned char encoder_onnx[];
    extern const unsigned int encoder_onnx_len;
    extern const unsigned char decoder_onnx[];
    extern const unsigned int decoder_onnx_len;
}
#endif

namespace llmzip {

struct InferenceEngine::Impl {
    sentencepiece::SentencePieceProcessor sp_processor;

    std::unique_ptr<Ort::Session> enc_session{nullptr};
    std::vector<const char*> enc_input_names;
    std::vector<const char*> enc_output_names;
    std::vector<Ort::AllocatedStringPtr> enc_input_names_ptrs;
    std::vector<Ort::AllocatedStringPtr> enc_output_names_ptrs;

    std::unique_ptr<Ort::Session> dec_session{nullptr};
    std::vector<const char*> dec_input_names;
    std::vector<const char*> dec_output_names;
    std::vector<Ort::AllocatedStringPtr> dec_input_names_ptrs;
    std::vector<Ort::AllocatedStringPtr> dec_output_names_ptrs;

    Ort::Env env{nullptr};
    Ort::SessionOptions session_options{nullptr};
    Ort::MemoryInfo memory_info{nullptr};

    bool initialized_ = false;
    int64_t max_seq_len = 512;
    int64_t max_new_tokens = 150;
    int64_t vocab_size = 32128;

    int64_t pad_token_id = 0;
    int64_t eos_token_id = 1;

    ~Impl() {
        dec_session.reset();
        enc_session.reset();
    }

    std::vector<int64_t> tokenize(const std::string& input) {
        std::vector<int> sp_ids;
        sp_processor.Encode(input, &sp_ids);
        std::vector<int64_t> tokens;
        for (int id : sp_ids) tokens.push_back(id);
        return tokens;
    }

    std::string detokenize(const std::vector<int64_t>& tokens) {
        std::vector<int> sp_ids;
        for (int64_t id : tokens) {
            if (id == pad_token_id || id == eos_token_id) continue;
            sp_ids.push_back((int)id);
        }
        std::string text;
        sp_processor.Decode(sp_ids, &text);
        return text;
    }

    bool run_encoder(const std::vector<int64_t>& input_ids, std::vector<float>& hidden_out) {
        std::vector<int64_t> ids(max_seq_len, pad_token_id);
        std::vector<int64_t> mask(max_seq_len, 0);
        for (size_t i = 0; i < std::min((size_t)max_seq_len, input_ids.size()); ++i) {
            ids[i] = input_ids[i];
            mask[i] = 1;
        }
        std::vector<int64_t> shape = {1, max_seq_len};
        std::vector<Ort::Value> inputs;
        inputs.push_back(Ort::Value::CreateTensor<int64_t>(memory_info, ids.data(), ids.size(), shape.data(), 2));
        inputs.push_back(Ort::Value::CreateTensor<int64_t>(memory_info, mask.data(), mask.size(), shape.data(), 2));

        auto outputs = enc_session->Run(Ort::RunOptions{nullptr}, enc_input_names.data(), inputs.data(), inputs.size(), enc_output_names.data(), enc_output_names.size());
        if (outputs.empty()) return false;
        auto info = outputs[0].GetTensorTypeAndShapeInfo();
        auto* data = outputs[0].GetTensorMutableData<float>();
        hidden_out.assign(data, data + info.GetElementCount());
        return true;
    }

    bool run_decoder(const std::vector<int64_t>& decoder_ids, const std::vector<float>& encoder_hidden, const std::vector<int64_t>& enc_input_ids, std::vector<float>& logits_out) {
        std::vector<int64_t> full_ids(max_seq_len, pad_token_id);
        std::vector<int64_t> attention_mask(max_seq_len, 0);
        for (size_t i = 0; i < std::min((size_t)max_seq_len, enc_input_ids.size()); ++i) {
            full_ids[i] = enc_input_ids[i];
            attention_mask[i] = 1;
        }
        size_t sep = std::min((size_t)max_seq_len - 1, enc_input_ids.size());
        full_ids[sep] = eos_token_id;
        attention_mask[sep] = 1;
        for (size_t i = 0; i < decoder_ids.size(); ++i) {
            size_t p = sep + 1 + i;
            if (p >= (size_t)max_seq_len) break;
            full_ids[p] = decoder_ids[i];
            attention_mask[p] = 1;
        }
        std::vector<int64_t> shape = {1, max_seq_len};
        std::vector<int64_t> h_shape = {1, max_seq_len, 512};
        
        std::vector<Ort::Value> inputs;
        for (size_t i = 0; i < dec_input_names.size(); ++i) {
            std::string name = dec_input_names[i];
            if (name == "input_ids") inputs.push_back(Ort::Value::CreateTensor<int64_t>(memory_info, full_ids.data(), full_ids.size(), shape.data(), 2));
            else if (name == "encoder_attention_mask") inputs.push_back(Ort::Value::CreateTensor<int64_t>(memory_info, attention_mask.data(), attention_mask.size(), shape.data(), 2));
            else if (name == "encoder_hidden_states") {
                inputs.push_back(Ort::Value::CreateTensor<float>(memory_info, const_cast<float*>(encoder_hidden.data()), encoder_hidden.size(), h_shape.data(), 3));
            } else {
                std::vector<int64_t> d(1, 0);
                inputs.push_back(Ort::Value::CreateTensor<int64_t>(memory_info, d.data(), 1, std::vector<int64_t>{1, 1}.data(), 2));
            }
        }
        auto outputs = dec_session->Run(Ort::RunOptions{nullptr}, dec_input_names.data(), inputs.data(), inputs.size(), dec_output_names.data(), dec_output_names.size());
        if (outputs.empty()) return false;
        auto* data = outputs[0].GetTensorMutableData<float>();
        int64_t last_pos = std::min<int64_t>(sep + decoder_ids.size(), max_seq_len - 1);
        logits_out.assign(data + last_pos * vocab_size, data + (last_pos + 1) * vocab_size);
        return true;
    }

    void query_info(Ort::Session* s, std::vector<const char*>& names, std::vector<Ort::AllocatedStringPtr>& ptrs) {
        Ort::AllocatorWithDefaultOptions alloc;
        for (size_t i = 0; i < s->GetInputCount(); ++i) {
            ptrs.push_back(s->GetInputNameAllocated(i, alloc));
            names.push_back(ptrs.back().get());
        }
    }
    void query_out_info(Ort::Session* s, std::vector<const char*>& names, std::vector<Ort::AllocatedStringPtr>& ptrs) {
        Ort::AllocatorWithDefaultOptions alloc;
        for (size_t i = 0; i < s->GetOutputCount(); ++i) {
            ptrs.push_back(s->GetOutputNameAllocated(i, alloc));
            names.push_back(ptrs.back().get());
        }
    }
};

InferenceEngine::InferenceEngine() : pimpl_(std::make_unique<Impl>()) {}
InferenceEngine::~InferenceEngine() = default;

bool InferenceEngine::initialize_embedded() {
#ifdef EMBED_MODEL
    try {
        if (spiece_model_len > 0) pimpl_->sp_processor.LoadFromSerializedProto(std::string((const char*)spiece_model, spiece_model_len));
        pimpl_->env = Ort::Env(ORT_LOGGING_LEVEL_WARNING, "llmzip");
        pimpl_->session_options = Ort::SessionOptions();
        pimpl_->session_options.SetIntraOpNumThreads(1);
        pimpl_->enc_session = std::make_unique<Ort::Session>(pimpl_->env, encoder_onnx, encoder_onnx_len, pimpl_->session_options);
        pimpl_->query_info(pimpl_->enc_session.get(), pimpl_->enc_input_names, pimpl_->enc_input_names_ptrs);
        pimpl_->query_out_info(pimpl_->enc_session.get(), pimpl_->enc_output_names, pimpl_->enc_output_names_ptrs);
        pimpl_->dec_session = std::make_unique<Ort::Session>(pimpl_->env, decoder_onnx, decoder_onnx_len, pimpl_->session_options);
        pimpl_->query_info(pimpl_->dec_session.get(), pimpl_->dec_input_names, pimpl_->dec_input_names_ptrs);
        pimpl_->query_out_info(pimpl_->dec_session.get(), pimpl_->dec_output_names, pimpl_->dec_output_names_ptrs);
        pimpl_->memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
        pimpl_->initialized_ = true;
        return true;
    } catch (...) { return false; }
#endif
    return false;
}

bool InferenceEngine::initialize(const std::string& p) { return initialize_embedded(); }

InferenceResult InferenceEngine::compress_text(const std::string& input) {
    InferenceResult res;
    if (!pimpl_->initialized_) return res;
    std::string prompted = "Protocol: Key:Value; Example: Input: Auth PR 42. Output: Dev: →review; Code: PR#42; Input: " + input + " Output:";
    auto ids = pimpl_->tokenize(prompted);
    if (ids.size() > 350) ids.resize(350);
    std::vector<float> hidden;
    if (!pimpl_->run_encoder(ids, hidden)) return res;
    std::vector<int64_t> dec_ids = {0};
    for (int i = 0; i < 150; ++i) {
        std::vector<float> logits;
        if (!pimpl_->run_decoder(dec_ids, hidden, ids, logits)) break;
        int best = std::distance(logits.begin(), std::max_element(logits.begin(), logits.end()));
        if (best == pimpl_->eos_token_id) break;
        dec_ids.push_back(best);
    }
    res.output_text = pimpl_->detokenize(dec_ids);
    res.success = true;
    return res;
}

InferenceResult InferenceEngine::decompress_text(const std::vector<uint8_t>& d) { return {}; }
std::string InferenceEngine::get_model_info() const { return "T5-FewShot"; }
std::vector<int64_t> InferenceEngine::tokenize_input(const std::string& i) { return pimpl_->tokenize(i); }
std::string InferenceEngine::detokenize_output(const std::vector<int64_t>& t) { return pimpl_->detokenize(t); }

}
